# fly.toml app configuration file generated for backend-nameless-bird-4512

app = 'backend-nameless-bird-4512'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 2

[mounts]
  source = "model_cache"
  destination = "/data"

[checks]
  [checks.health]
    type = "http"
    interval = "30s"
    timeout = "10s"
    method = "get"
    path = "/health"
    grace_period = "30s"
