services:
  - type: web
    name: dan-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8080
    envVars:
      - key: OPENROUTER_API_KEY
        value: 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
    plan: starter
